# File auto-generated by Charles Bucher
# Repo: CloudOpsLab
# Role: Cloud Support & CloudOps Engineer
# Skills: AWS (EC2, S3, Lambda, VPC, RDS, DynamoDB), Python, Terraform, CloudFormation, CloudWatch, IAM, SNS/SQS, CI/CD, Automation, Troubleshooting
# Email: quietopscb@gmail.com
# GitHub: https://github.com/charles-bucher
# Portfolio: https://charles-bucher.github.io/
